### ISSUE TITLE
Development Map

### ISSUE THREAD

**Issue by LT-Rascek** [loup99/BP#9]
@loup99: While working on culture/innovations and hit some annoying roadblocks, so I spent some time mapping out dependencies between game concepts. I put this together in about 20 minutes, so I might have missed some of the dependencies; I can update it more if necessary.

Blue indicates history aspects (i.e., making the map, characters, and situation that match the 476 start), while purple indicates things in the common/ folder that relate to nice WtWSMS chrome (e.g., migration and Roman Reconquest Casus Belli, Religious events like the Henotikon and Three Chapters Controversy, Restoration of Rome and Rebuilding the Circus Maximums). This will also better explain the relationship between some items that should make linking things together easier.

Short story: Cultures and Religions are the biggest blockers at the moment and we should focus on getting those stamped out in the near term; that greatly opens up the things we can develop without having to backtrack.

Might be useful to set up a wiki for storing this sort of info rather than issues; a central repository is always useful.

![development_map](https://user-images.githubusercontent.com/55886300/94745548-e9349c80-0348-11eb-9330-785ab055f68a.PNG)

A graphmp file used to build the above diagram in yEd.
[Development_Map.zip](https://github.com/loup99/BP/files/5308521/Development_Map.zip)

**Comment by loup99** [comment]
Thank you for taking the time to do this map.

> Short story: Cultures and Religions are the biggest blockers at the moment and we should focus on getting those stamped out in the near term; that greatly opens up the things we can develop without having to backtrack.

Agreed, that is why we divided tasks so that cultures and religions could advance right away.

> Might be useful to set up a wiki for storing this sort of info rather than issues; a central repository is always useful.

Do you mean a wiki on the repository or something else? Because I believe the "wiki" tab is active.

**Comment by LT-Rascek** [comment]
I keep getting redirected to the code tab when I click the wiki tab. I don't know if anyone else ran into that problem.

**Comment by loup99** [comment]
> I keep getting redirected to the code tab when I click the wiki tab. I don't know if anyone else ran into that problem.

I believe it should be fixed, unless there is some permission issue.

**Comment by LT-Rascek** [comment]
I still can't edit it; it seems to be a permissions issue; people might need to be collaborators to edit wikis.

**Comment by loup99** [comment]
> I still can't edit it; it seems to be a permissions issue; people might need to be collaborators to edit wikis.

Ok, I will add you then

**Comment by LT-Rascek** [comment]
Updated the wiki with this, so it shouldn't be left as an issue anymore.
